name: this ole dog
favicon: null
layout_spectrum: 0.29268
typography_spectrum: 0.5007936886977404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9c28c'
    - '#383121'
    - '#ad987d'
    - '#68604d'
    - '#c85b30'
  brandStrength: 0.3125
  lightness: 0.8151315120048821
  saturation: 0.8192679616622627
  rhythmicContrast: 0.5587367708794773
purpose: []
