name: this ole dog
favicon: null
layout_spectrum: 0.29268
typography_spectrum: 0.13423
title: This Ole Dog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2e8ab'
    - '#000000'
    - '#b9b19e'
    - '#5b6f78'
    - '#e96638'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
