name: this ole dog
favicon: null
layout_spectrum: 0.2472291688900441
typography_spectrum: 0.6916822565253824
title: This Ole Dog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2e8ab'
    - '#000000'
    - '#b9b19e'
    - '#5b6f78'
    - '#e96638'
  brandStrength: 0.4387418399564922
  lightness: 0.47741020494140685
  saturation: 0.6739513375796378
  rhythmicContrast: 0.453366065165028
purpose: []
