name: this ole dog
favicon: null
layout_spectrum: 0.29268
typography_spectrum: 0.13423
title: This Ole Dog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9c28c'
    - '#383121'
    - '#ad987d'
    - '#68604d'
    - '#c85b30'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
