name: this ole dog
favicon: null
layout_spectrum: 0.6673159333877265
typography_spectrum: 0.6916822565253824
title: This Ole Dog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2e8ab'
    - '#000000'
    - '#b9b19e'
    - '#5b6f78'
    - '#e96638'
  brandStrength: 0.19036618201062083
  lightness: 0.26199227571487427
  saturation: 0.5184124724473804
  rhythmicContrast: 0.8619360066950321
purpose: []
